name: "Build Notesnook Web"
on:
    push:
        paths: 'release-versions/notesnook-web.txt'
    
    workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: 'soundofdarkness/notesnook-web'

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
          packages: write
          contents: read
          attestations: write
          id-token: write
        steps:
            - uses: actions/checkout@v4
              name: "Fetch build repository"

            - name: "Get Version"
              run: |
                 version=$(<"./release-versions/notesnook-web.txt")
                 echo "NOTESNOOK_VERSION=${version}" >> "$GITHUB_ENV"
            - uses: actions/checkout@v4
              name: "Fetch Notesnook repository"
              with:
                repository: "streetwriters/notesnook"
                path: 'notesnook'
                ref: ${{ env.NOTESNOOK_VERSION }}
            
            - uses: actions/setup-node@v4
              with:
                node-version: 'lts/iron'
                check-latest: true
            
            - name: "Install Dependencies"
              run: |
                cd notesnook
                npm ci --ingore-scripts --prefer-offline --no-audit
                npm run bootstrap -- --scope=web
            
            - name: "Build Webapp"
              run: |
                cd notesnook
                npm run build:web
            
            - name: "GHCR Login"
              uses: docker/login-action@v3.3.0
              with:
                registry: ${{ env.REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            
            - name: "Build and Push Image"
              uses: docker/build-push-action@v6.9.0
              id: push
              with:
                context: .
                push: true
                tags: ${{ format('{0}/{1}:{2}','ghcr.io', env.IMAGE_NAME, env.NOTESNOOK_VERSION)}}
            
            - name: "Generate artifact attestation"
              uses: actions/attest-build-provenance@v1.4.4
              with:
                subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
                subject-digest: ${{ steps.push.outputs.digest }}
                push-to-registry: true

                
